### PR TITLE
Merge customCSS inside main CSS

### PR DESCRIPTION
**Pull request by forty**
It will allow to load a single file.

### CODE REVIEW

**Comment by Mitrichius** [comment]
Thanks!

**Comment by HorayNarea** [comment]
Since this change, when I run `hugo server` it throws the following error.

```
Start building sites …
hugo v0.88.1+extended linux/amd64 BuildDate=unknown
Error: Error building site: EXECUTE-AS-TEMPLATE: failed to transform "css/main.css" (text/css): template: css/main.css:587:14: executing "css/main.css" at <$custom.Content>: nil pointer evaluating resource.Resource.Content
Built in 747 ms
```

In my `config.toml` I have this:

```toml
[params]
customCSS = ["css/custom.css"]
```

and in `static/css/custom.css` are simple custom CSS rules.


Am I doing something wrong or is something broken?

**Comment by Mitrichius** [comment]
@HorayNarea 
After this change, it is necessary to install an extended version of Hugo to run theme

https://gohugo.io/getting-started/installing/ - search "Extended"

**Comment by HorayNarea** [comment]
As you can see in the error, this is an extended version:
`hugo v0.88.1+extended linux/amd64 BuildDate=unknown`

**Comment by Mitrichius** [comment]
Sorry, I wasn't paying attention to this.
Try to move `static/css/custom.css` to `assets/css/custom.css` without changing config.

**Comment by HorayNarea** [comment]
Thanks, that fixes my problem!

**Pull request merged**
