### PR TITLE
add isso comment to posts

### PR DESCRIPTION
**Pull request by cambid**
This PR adds code for using [ISSO](https://posativ.org/isso/) as a comment system.

### CODE REVIEW

**Comment by Mitrichius** [comment]
Need to update the example of config.yaml in Readme with isso mandatory/optional params (like it was made for utteranc.es)

**Comment by cambid** [comment]
@Mitrichius: Good Idea. I will push a commit with an update to the README.

**Comment by cambid** [comment]
> @Mitrichius: Good Idea. I will push a commit with an update to the README.

done

**Comment by Mitrichius** [comment]
Merged, thanks!

**Pull request merged**
